import { StyleSheet } from 'react-native';

import { Colors, Gradients, BorderRadius } from '@/theme';

export const homeStyles = StyleSheet.create({
  header: {
    marginBottom: 30,
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  profileButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  greeting: {
    fontSize: 32,
    fontWeight: '800',
    color: Colors.textPrimary,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 16,
    color: Colors.textMuted,
    marginTop: 5,
    fontWeight: '500',
  },

  // ─── Balance Card ──────────────────────────────────────
  balanceCard: {
    borderRadius: BorderRadius.xl,
    padding: 24,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 35,
    borderWidth: 1,
    borderColor: Colors.borderMedium,
    overflow: 'hidden',
  },
  balanceLabel: {
    color: Colors.textLabel,
    fontSize: 14,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 5,
  },
  balanceValue: {
    color: Colors.textPrimary,
    fontSize: 36,
    fontWeight: '900',
    letterSpacing: -1,
  },
  topUpButton: {
    backgroundColor: Colors.bgSurfaceMedium,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: BorderRadius.lg,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.bgSurfaceBright,
  },
  topUpText: {
    color: Colors.textPrimary,
    fontWeight: '700',
    marginLeft: 4,
    fontSize: 14,
  },

  // ─── Action Grid ───────────────────────────────────────
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  gridItemAnimated: {
    width: '48%',
    marginBottom: 15,
  },
  gridItemInner: {
    backgroundColor: Colors.bgSurface,
    padding: 20,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    borderColor: Colors.bgSurfaceLight,
    alignItems: 'center',
    height: 160,
    justifyContent: 'center',
  },
  gridItem: {
    width: '48%',
    backgroundColor: Colors.bgSurface,
    padding: 20,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    borderColor: Colors.bgSurfaceLight,
    alignItems: 'center',
    height: 160,
    marginBottom: 15,
    justifyContent: 'center',
  },
  iconContainer: {
    width: 60,
    height: 60,
    borderRadius: BorderRadius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 15,
  },
  gridLabel: {
    color: Colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 4,
  },
  gridSubLabel: {
    color: Colors.textDimmed,
    fontSize: 12,
    textAlign: 'center',
    fontWeight: '500',
  },
  gridItemSecondary: {
    width: '100%',
    backgroundColor: Colors.bgSurface,
    padding: 20,
    borderRadius: BorderRadius.xl,
    borderWidth: 1,
    borderColor: Colors.bgSurfaceLight,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 5,
  },
  iconContainerSm: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gridLabelSecondary: {
    color: Colors.textPrimary,
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 2,
  },
  gridSubLabelSecondary: {
    color: Colors.textDimmed,
    fontSize: 14,
    fontWeight: '500',
  },
});
